WEB2020Apr_P03_T4/Models/FlightSchedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace WEB2020Apr_P03_T4.Models
{
    public class FlightSchedule
    {
        [Required]
        public int ScheduleID { get; set; }
        [Required]
        public string FlightNumber { get; set; }
        [Required]
        public int RouteID { get; set; }

        public int AircraftID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime? DepartureDateTime { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? ArrivalDateTime { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public double EconomyClassPrice { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public double BusinessClassPrice { get; set; }
        [Required]
        public string Status { get; set; }
    }
}

WEB2020Apr_P03_T4/Models/FlightScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB2020Apr_P03_T4.Models
{
    public class FlightScheduleViewModel
    {
        [Display (Name = "Aircraft ID")]
        public int AircraftID { get; set; }
        [Display(Name ="Schedule ID")]
        public int ScheduleID { get; set; }

        [Display(Name = "Flight Number")]

        public string FlightNumber { get; set; }

        [Display (Name = "Departure Date and Time")]

        public DateTime? DepartureDateTime { get; set; }

        [Display (Name = "Arrival Date and Time")]

        public DateTime? ArrivalDateTime { get; set; }

        [Display (Name = "City of Departure")]

        public string DepartureCity { get; set; }

        [Display (Name = "City of Arrival")]

        public string ArrivalCity { get; set; }


    }
}

WEB2020Apr_P03_T4/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB2020Apr_P03_T4.Models;
using WEB2020Apr_P03_T4.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace WEB2020Apr_P03_T4.Controllers
{
    public class BookingController : Controller
    {
        private PackageOneDAL customerContext = new PackageOneDAL();
        private Package2DAL package2DB = new Package2DAL();

        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }

        // GET: Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Booking/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Booking/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        //qh - used to show bookings for schedule
        public ActionResult Package2List(int id)
        {
            ViewData["ScheduleID"] = id;
            List<Booking> bookingList = package2DB.GetBookingsForSchedule(id);
            return View(bookingList);
        }

        public ActionResult ViewBooking(int id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Customer"))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<Booking> bookingList = new List<Booking>();
                bookingList = customerContext.GetBookingsForCustomer(id);
                return View(bookingList);
            }
        }
    }
}

WEB2020Apr_P03_T4/Controllers/FlightRouteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB2020Apr_P03_T4.Models;
using WEB2020Apr_P03_T4.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WEB2020Apr_P03_T4.Controllers
{
    public class FlightRouteController : Controller
    {
        private Package2DAL package2DB = new Package2DAL();

        // GET: FlightRoute
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }

            List<FlightRoute> routeList = package2DB.GetFlightRoutes();
            return View(routeList);
        }

        // GET: FlightRoute/Details/5
        public ActionResult Details(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: FlightRoute/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: FlightRoute/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightRoute flightroute)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                //qh - Add FlightRoute record to database
                flightroute.RouteID = package2DB.AddFlightRoute(flightroute);
                //Redirect user to FlightSchedule/Index view 
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view         
                //to display error message 
                return View(flightroute);
            }
        }

        // GET: FlightRoute/Edit/5
        //qh - UNUSED
        public ActionResult Edit(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: FlightRoute/Edit/5
        //qh - UNUSED
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightRoute/Delete/5 UNUSED
        //qh - UNUSED
        public ActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: FlightRoute/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WEB2020Apr_P03_T4/Controllers/FlightScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB2020Apr_P03_T4.Models;
using WEB2020Apr_P03_T4.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WEB2020Apr_P03_T4.Controllers
{
    public class FlightScheduleController : Controller
    {
        private Package2DAL package2DB = new Package2DAL();

        // GET: FlightSchedule
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            //qh - gets all flight schedules
            List<FlightSchedule> scheduleList = package2DB.GetFlightSchedules();
            return View(scheduleList);
        }

        // GET: FlightSchedule/Details/5
        public ActionResult Details(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: FlightSchedule/Create
        public ActionResult Create(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            FlightSchedule created = new FlightSchedule();
            created.RouteID = id;

            System.Diagnostics.Debug.WriteLine(id);
            System.Diagnostics.Debug.WriteLine(created.RouteID);
            //qh - data to be showed in the html page
            ViewData["RouteList"] = getroutes();
            ViewData["AircraftList"] = getaircraft();
            ViewData["ID"] = id;
            return View(created);
        }

        // POST: FlightSchedule/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightSchedule flightschedule)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            System.Diagnostics.Debug.WriteLine(flightschedule.RouteID);
            ViewData["RouteList"] = getroutes();
            ViewData["AircraftList"] = getaircraft();

            //qh- make sure departure date cannot be today or before today
            if (flightschedule.DepartureDateTime.Value.Date <= DateTime.Today.Date && flightschedule.DepartureDateTime.Value.Year <= DateTime.Today.Year)
            {
                ViewData["ID"] = flightschedule.RouteID;
                ViewData["Error"] = "Date must be one day after today!";
                return View(flightschedule);
            }

            //qh - auto adds the duration to arrival date time
            FlightRoute current = package2DB.FindSpecificFlightRoute(flightschedule.RouteID);
            int duration = current.FlightDuration;
            flightschedule.ArrivalDateTime = flightschedule.DepartureDateTime.Value.AddHours(duration);

            if (ModelState.IsValid)
            {
                //Add FlightSchedule record to database
                flightschedule.ScheduleID = package2DB.AddFlightSchedule(flightschedule);
                //Redirect user to FlightSchedule/Index view 
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view         
                //to display error message 
                return View(flightschedule);
            }
        }


        // GET: FlightSchedule/Edit/5
        public ActionResult EditStatus(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            FlightSchedule current = package2DB.FindSpecificFlightSchedule(id);
            System.Diagnostics.Debug.WriteLine(current.ScheduleID);
            return View(current);
        }

        // POST: FlightSchedule/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditStatus(FlightSchedule current)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            //qh - db code to update status
            System.Diagnostics.Debug.WriteLine(current.ScheduleID);
            package2DB.UpdateStatus(current);
            return RedirectToAction("Index");
        }

        // GET: FlightSchedule/Delete/5
        public ActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            FlightSchedule current = package2DB.FindSpecificFlightSchedule(id);
            System.Diagnostics.Debug.WriteLine(current.ScheduleID);

            return View(current);
        }

        // POST: FlightSchedule/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FlightSchedule current)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            System.Diagnostics.Debug.WriteLine(current.ScheduleID);
            package2DB.DeleteFlightSchedule(current.ScheduleID);
            return RedirectToAction("Index");
        }

        //for view data
        public List<SelectListItem> getroutes()
        {
            List<FlightRoute> routelist = package2DB.GetFlightRoutes();
            List<SelectListItem> routeselectlist = new List<SelectListItem>();
            foreach (FlightRoute i in routelist)
            {
                routeselectlist.Add(new SelectListItem { Value = Convert.ToString(i.RouteID), Text = Convert.ToString(i.RouteID) });
            }
            return routeselectlist;
        }
        //for view data
        public List<SelectListItem> getaircraft()
        {
            List<Aircraft> aircrafts = package2DB.GetAircraft();
            List<SelectListItem> aircraftselectlist = new List<SelectListItem>();
            foreach (Aircraft i in aircrafts)
            {
                aircraftselectlist.Add(new SelectListItem { Value = Convert.ToString(i.AircraftID), Text = Convert.ToString(i.AircraftID) });
            }
            return aircraftselectlist;
        }

        public ActionResult ListSpecific(int id)
        {
            if (HttpContext.Session.GetString("Role") != "Staff")
            {
                return RedirectToAction("Index", "Home");
            }
            List<FlightSchedule> scheduleList = package2DB.GetFlightSchedulesForRoutes(id);
            return View(scheduleList);
        }
    }
}

WEB2020Apr_P03_T4/Views/FlightSchedule/Delete.cshtml
@model WEB2020Apr_P03_T4.Models.FlightSchedule

@{
    ViewData["Title"] = "Delete";
}
<!-- Done by QH -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/package2.css" />
</head>
<body class="backgroundimgp2main">
    <div class="container" style="background-color:rgba(255,255,255,0.75);width:100%;border-radius:5px;padding-top:1px;">
        <h1 class="newtextclassheading">Delete Flight Schedule</h1>

        <form asp-action="Delete">
            <fieldset class="FormContent">
                <legend>Are you sure you want to delete this record?</legend>
                <div class="form-group row">
                    <label asp-for="ScheduleID" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 col-md-5">
                        <input asp-for="ScheduleID" readonly class="form-control-plaintext" />
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="FlightNumber" class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-9 col-md-5">
                        <input asp-for="FlightNumber" readonly class="form-control-plaintext" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-9 offset-sm-3">
                        <input type="submit" value="Delete" class="btn btn-primary deletebutton" />
                    </div>
                </div>

                <div>
                    <a asp-action="Index">Back to List</a>
                </div>

            </fieldset>
        </form>
    </div>
</body>
</html>

WEB2020Apr_P03_T4/Views/FlightSchedule/EditStatus.cshtml
@model WEB2020Apr_P03_T4.Models.FlightSchedule

@{
    ViewData["Title"] = "EditStatus";
}

<!-- Done by QH -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/package2.css" />
</head>
<body class="backgroundimgFlightSchedule">
    <div class="container" style="background-color:rgba(255,255,255,0.75);width:100%;border-radius:5px;padding-top:1px;">
        <h1 class="newtextclassheading">Edit Status</h1>
        <hr />
        <div class="form-group row morepadding" style="justify-content: center; align-items: center">
            <a class="btn btn-primary deletebutton morepadding" asp-controller="FlightSchedule" asp-action="Index">Back to Flight Schedules</a>
        </div>
        <div class="container">
            <form asp-action="EditStatus">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input style="display: none;" asp-for="ScheduleID" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="FlightNumber" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="RouteID" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="AircraftID" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="DepartureDateTime" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="ArrivalDateTime" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="EconomyClassPrice" readonly class="form-control-plaintext" />
                    <input style="display: none;" asp-for="BusinessClassPrice" readonly class="form-control-plaintext" />
                    <label asp-for="Status" class="control-label"></label>
                    <select asp-for="Status" class="form-control inputbox">
                        <option value="Cancelled">Cancelled</option>
                        <option value="Delayed">Delayed</option>
                        <option value="Full">Full</option>
                        <option value="Opened">Opened</option>
                    </select>
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
                <div class="form-group row morepadding" style="justify-content: center; align-items: center">
                    <input type="submit" value="Save" class="btn btn-primary deletebutton morepadding" />
                </div>
            </form>
        </div>
    </div>
    
</body>
</html>

WEB2020Apr_P03_T4/Views/FlightSchedule/Index.cshtml
@model IEnumerable<WEB2020Apr_P03_T4.Models.FlightSchedule>

@{
    ViewData["Title"] = "Index";
}
<!-- Done by QH -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/package2.css" />
</head>
<body class="backgroundimgFlightSchedule">
    <div class="container" style="display: table;background-color:rgba(255,255,255,0.75);width:100%;border-radius:5px;padding-top:1px;">
        <h1 class="newtextclassheading">View All Flight Schedules</h1>
        <div class="form-group row morepadding" style="justify-content: center; align-items: center">
            <a class="btn btn-primary deletebutton morepadding" asp-controller="FlightRoute" asp-action="Index">Back to Flight Routes</a>
        </div>
        <table class="table">
            <thead class="tableheadcolor">
                <tr class="tableborder">
                    <th class="textclassinput">
                        Schedule ID
                    </th>
                    <th class="textclassinput">
                        Flight Number
                    </th>
                    <th class="textclassinput">
                        Route ID
                    </th>
                    <th class="textclassinput">
                        Aircraft ID
                    </th>
                    <th class="textclassinput">
                        Departure Date and Time
                    </th>
                    <th class="textclassinput">
                        Arrival Date and Time
                    </th>
                    <th class="textclassinput">
                        Economy Class Price
                    </th>
                    <th class="textclassinput">
                        Business Class Price
                    </th>
                    <th class="textclassinput">
                        Status
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="tableborder">
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.ScheduleID)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.FlightNumber)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.RouteID)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.AircraftID)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.DepartureDateTime)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.ArrivalDateTime)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.EconomyClassPrice)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.BusinessClassPrice)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td class="textclassinput">
                            <a asp-action="Package2List" asp-controller="Booking" asp-route-id="@item.ScheduleID">View Ticket Bookings</a> |
                            <a asp-action="Delete" asp-controller="FlightSchedule" asp-route-id="@item.ScheduleID">Delete</a> |
                            <a asp-action="EditStatus" asp-controller="FlightSchedule" asp-route-id="@item.ScheduleID">Edit Status</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="form-group row morepadding" style="justify-content: center; align-items: center">
            <a class="btn btn-primary deletebutton morepadding" asp-area="" asp-controller="Home" asp-action="Package2Main">Back to Main</a>
        </div>
    </div>
    
</body>
</html>

WEB2020Apr_P03_T4/Views/FlightSchedule/ListSpecific.cshtml
@model IEnumerable<WEB2020Apr_P03_T4.Models.FlightSchedule>

@{
    ViewData["Title"] = "Index";
}
<!-- Done by QH -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/package2.css" />
</head>
<body class="backgroundimgFlightSchedule">
    <div class="container" style="background-color:rgba(255,255,255,0.75);width:100%;border-radius:5px;padding-top:1px;display:table">
        <h1 class="newtextclassheading">View All Flight Schedules</h1>
        <div class="form-group row morepadding" style="justify-content: center; align-items: center">
            <a class="btn btn-primary deletebutton morepadding" asp-controller="FlightRoute" asp-action="Index">Back to Flight Routes</a>
        </div>
        <table class="table">
            <thead class="tableheadcolor">
                <tr class="tableborder">
                    <th>
                        @Html.DisplayNameFor(model => model.ScheduleID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FlightNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RouteID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AircraftID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DepartureDateTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ArrivalDateTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EconomyClassPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BusinessClassPrice)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="tableborder">
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.ScheduleID)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.FlightNumber)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.RouteID)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.AircraftID)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.DepartureDateTime)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.ArrivalDateTime)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.EconomyClassPrice)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.BusinessClassPrice)
                        </td>
                        <td class="textclassinput">
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td class="textclassinput">
                            <a asp-action="Package2List" asp-controller="Booking" asp-route-id="@item.ScheduleID">View Ticket Bookings</a> |
                            <a asp-action="Delete" asp-controller="FlightSchedule" asp-route-id="@item.ScheduleID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="form-group row morepadding" style="justify-content: center; align-items: center">
            <a class="btn btn-primary deletebutton morepadding" asp-area="" asp-controller="Home" asp-action="Package2Main">Back to Main</a>
        </div>
    </div> 
</body>
</html>