WEB2020Apr_P03_T4/Controllers/AircraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Group4WEB.DAL;
using WEB2020Apr_P03_T4.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Cryptography.Xml;

namespace Group4WEB.Controllers
{
    public class AircraftController : Controller
    {
        Package4DAL packageDAL = new Package4DAL();
        // GET: Aircraft
        public ActionResult Index()
        {
            List<AircraftViewModel> aircraftViewModels = new List<AircraftViewModel>();
            List<Aircraft> aircrafts = packageDAL.GetAircraft();
            foreach (Aircraft a in aircrafts)
            {
                AircraftViewModel aircraftVM = MapToAircraftVM(a);
                aircraftViewModels.Add(aircraftVM);

            }
            return View(aircraftViewModels);

        }
        public AircraftViewModel MapToAircraftVM(Aircraft aircraft)
        {
            List<FlightScheduleViewModel> AllFlightSchedules = new List<FlightScheduleViewModel>();
            List<FlightScheduleViewModel> AircraftFlights = new List<FlightScheduleViewModel>();
            string departureCity = "";
            string arrivalCity = "";
            DateTime? departuretime = null, arrivalTime = null;
            List<FlightSchedule> flights = packageDAL.GetFlightSchedules();
            List<FlightRoute> routes = packageDAL.GetFlightRoutes();
            foreach (FlightSchedule f in flights)
            {

                if (f.AircraftID == aircraft.AircraftID)
                {

                    departuretime = f.DepartureDateTime;
                    arrivalTime = f.ArrivalDateTime;
                    foreach (FlightRoute r in routes)
                    {
                        if (r.RouteID == f.RouteID)
                        {
                            FlightScheduleViewModel vm = new FlightScheduleViewModel
                            {
                                ArrivalCity = r.ArrivalCity,
                                DepartureCity = r.DepartureCity,
                                ArrivalDateTime = f.ArrivalDateTime,
                                DepartureDateTime = f.DepartureDateTime,
                                FlightNumber = f.FlightNumber,
                                ScheduleID = f.ScheduleID
                            };
                            AircraftFlights.Add(vm);
                            departureCity = r.DepartureCity;
                            arrivalCity = r.ArrivalCity;
                            break;
                        }
                    }

                }

            }
            foreach (FlightSchedule f in flights)
            {

                foreach (FlightRoute r in routes)
                {
                    if (f.RouteID == r.RouteID && f.AircraftID != aircraft.AircraftID)
                    {
                        FlightScheduleViewModel vm = new FlightScheduleViewModel
                        {
                            ArrivalCity = r.ArrivalCity,
                            DepartureCity = r.DepartureCity,
                            ArrivalDateTime = f.ArrivalDateTime,
                            DepartureDateTime = f.DepartureDateTime,
                            FlightNumber = f.FlightNumber,
                            AircraftID = f.AircraftID,
                            ScheduleID = f.ScheduleID
                        };
                        AllFlightSchedules.Add(vm);
                    }

                }

            }

            AircraftViewModel aircraftVM = new AircraftViewModel
            {
                AircraftID = aircraft.AircraftID,
                DateOfLastMaintenance = aircraft.DateLastMaintenance,
                MakeModel = aircraft.MakeModel,
                NumBusinessSeat = aircraft.NumBusinessSeat,
                NumEconomySeat = aircraft.NumEconomySeat,
                DateLastMaintenance = aircraft.DateLastMaintenance,
                DepartureCity = departureCity,
                ArrivalCity = arrivalCity,
                DepartureDateTime = departuretime,
                ArrivalDateTime = arrivalTime,
                AircraftHistory = AircraftFlights,
                AllFlights = AllFlightSchedules,
                Status = aircraft.Status



            };
            return aircraftVM;


        }


        // GET: Aircraft/Details/5
        public ActionResult Details(int id)
        {
            Aircraft aircraft = packageDAL.GetAircraftDetails(id);
            AircraftViewModel aircraftVM = MapToAircraftVM(aircraft);
            return View(aircraftVM);
        }

        // GET: Aircraft/Create
        public ActionResult Create()
        {
            ViewData["StatusList"] = GetStatus();
            return View();


        }

        private List<SelectListItem> GetStatus()
        {
            List<SelectListItem> statuses = new List<SelectListItem>();
            statuses.Add(new SelectListItem { Value = "Operational", Text = "Operational" });
            statuses.Add(new SelectListItem { Value = "Under Maintenance", Text = "Under Maintenance" });
            return statuses;

        }
        private List<SelectListItem> GetAircraft()
        {
            List<SelectListItem> statuses = new List<SelectListItem>();
            List<Aircraft> aircrafList = packageDAL.GetAircraft();
            foreach (Aircraft a in aircrafList)
            {
                if (a.Status == "Operational")
                {
                    statuses.Add(new SelectListItem { Value = a.AircraftID.ToString(), Text = a.AircraftID.ToString() });
                }
            }
            return statuses;
        }
        // POST: Aircraft/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                aircraft.AircraftID = packageDAL.AddAircraft(aircraft);

                return RedirectToAction("Index");
            }
            else
            {
                return View(aircraft);
            }
        }
        public ActionResult Edit (int id)
        {
            ViewData["AircraftID"] = GetAircraft();
            FlightSchedule f = packageDAL.FindSpecificFlightSchedule(id);
            return View(f);
        }
        // POST: Aircraft/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int AircraftID, int ScheduleID)
        {
            packageDAL.AssignAircraft(AircraftID,ScheduleID);
            return RedirectToAction("Index");

        }
        public ActionResult EditStatus(int id)
        {
            ViewData["StatusList"] = GetStatus();
            Aircraft aircraft = packageDAL.GetAircraftDetails(id);
            return View(aircraft);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditStatus(Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                List<FlightSchedule> fList = packageDAL.GetAircraftFlights(aircraft.AircraftID);
                foreach (FlightSchedule f in fList)
                {
                    if (f.DepartureDateTime>DateTime.Now)
                    {
                        TempData["Message"] = "Aircraft has a pending flight!";
                        return View();
                    }
                    else
                    {
                        packageDAL.UpdateStatus(aircraft);
                    }
                }
                

                return RedirectToAction("Index");
            }
            else
            {
                return View(aircraft);
            }
        }
    }
}

WEB2020Apr_P03_T4/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WEB2020Apr_P03_T4.Models;
using WEB2020Apr_P03_T4.DAL;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace WEB2020Apr_P03_T4.Controllers
{
    public class BookingController : Controller
    {
        private PackageOneDAL customerContext = new PackageOneDAL();
        private Package2DAL package2DB = new Package2DAL();

        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }

        // GET: Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Booking/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Booking/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        //qh - used to show bookings for schedule
        public ActionResult Package2List(int id)
        {
            ViewData["ScheduleID"] = id;
            List<Booking> bookingList = package2DB.GetBookingsForSchedule(id);
            return View(bookingList);
        }

        public ActionResult ViewBooking(int id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Staff" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Customer"))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<Booking> bookingList = new List<Booking>();
                bookingList = customerContext.GetBookingsForCustomer(id);
                return View(bookingList);
            }
        }
    }
}

WEB2020Apr_P03_T4/Controllers/StaffMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WEB2020Apr_P03_T4.Controllers
{
    public class StaffMainController : Controller
    {
        // GET: StaffMain
        public ActionResult Index()
        {
            return View();
        }
        public IActionResult Package4Main()
        {
            return View();
        }
    }
}

WEB2020Apr_P03_T4/Views/Shared/Package1Main.cshtml
@{
    ViewData["Title"] = "Package1Main";
}

<h1>Package1Main</h1>

<a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="RegisterView">Register</a>

<a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Changepw">Change password</a>

WEB2020Apr_P03_T4/Views/Shared/_CustomerMenu.cshtml
@using Microsoft.AspNetCore.Http;

<nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img id="imgMainPic" src="~/images/blueplane.jpg" class="img" style="display:block;" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="News">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Country" asp-action="Index">Covid-19 Cases</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="FlightBooking" asp-route-id="@Context.Session.GetString("ScheduleID")">Book a flight</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Booking" asp-action="ViewBooking" asp-route-id="@Context.Session.GetString("CustomerID")">View Bookings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="Changepw" asp-route-id="@Context.Session.GetString("CustomerID")">Change Password</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Logout">Log Out</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

WEB2020Apr_P03_T4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group4WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/navbar.css" />
</head>
<body>
    <header>
        @if (Context.Session.GetString("Role") == null)
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3" style="margin-bottom:20px">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img id="imgMainPic" src="~/images/blueplane.jpg" class="img" style="display:block;" />
                    </a>
                    <button class="navbar-toggler" style="background-color:white;border-color: dodgerblue;border-width:3px; "type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span style="color:gray" class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="News">News</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Country" asp-action="Index">Covid-19 Cases</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
        else if (Context.Session.GetString("Role") != null)
        {
            if (Context.Session.GetString("Role") == "Staff")
            {
                @await Html.PartialAsync("_StaffMenu.cshtml");

            }
            if (Context.Session.GetString("Role") == "Customer")
            {
                @await Html.PartialAsync("_CustomerMenu.cshtml");
            }

        }
    </header>
    <div class="container">
        <main role="main" class="pb-3" >
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="margin-top:50px; background-color:rgba(255,255,255,0.4)">
        <div class="container" style="color:black">
            &copy; 2020 - Group4WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WEB2020Apr_P03_T4/Views/Shared/_StaffMenu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <img id="imgMainPic" src="~/images/blueplane.jpg" class="img" style="display:block;" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="StaffMain" asp-action="Index">Staff Main</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Package2Main">Flight Scheduling (Package 2)</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="~/Home/Package3Main">Package 3 Main</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " asp-area="" asp-controller="Aircraft" asp-action="Index">Aircraft </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Logout">Log Out</a>
                </li>

            </ul>
        </div>
    </div>
</nav>